# Generated by Django 2.2.5 on 2019-10-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191006_1713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Subscriber',
        ),
    ]
