# Generated by Django 2.2.5 on 2019-10-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191008_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber',
            new_name='Subs',
        ),
    ]
