# Generated by Django 2.2.5 on 2019-10-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_msg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msg',
        ),
    ]
