# Generated by Django 2.2.5 on 2019-10-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
