# Generated by Django 2.2.5 on 2019-10-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_massage_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='sub',
            field=models.CharField(default='news', max_length=255),
        ),
        migrations.AlterField(
            model_name='massage',
            name='text',
            field=models.CharField(max_length=5555),
        ),
    ]
