# Generated by Django 2.2.5 on 2019-10-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191029_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='sub',
            field=models.CharField(max_length=255),
        ),
    ]
