# Generated by Django 2.2.5 on 2019-10-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('num', models.IntegerField()),
                ('date', models.IntegerField()),
                ('guest', models.IntegerField()),
                ('time', models.IntegerField()),
            ],
        ),
    ]
